name: CI on Push and Pull Request

on: push

jobs:
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build APK
      run: |
        cd Android
        msbuild EindProject.Android.csproj /r:True /t:SignAndroidPackage /p:AndroidSdkDirectory=/android/sdk 
    - name: Artifacts
      run: |
        mkdir -p apks
        cp ./bin/*.apk apks
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: apks
        path: apks
